### PR TITLE
pedantic doc update - "missing be"

### PR DESCRIPTION
**Pull request by GetContented**
Just added the verb to the last clause "as _ would be" rather than "as _ would."

### CODE REVIEW

**Comment by bergey** [comment]
@GetContented I'm finally doing some PR triage.  If you can rebase just your documentation commit on top of current `master`, I'll merge it.

**Comment by GetContented** [comment]
Sorry I have no idea how to do that, becuase I'm just using the github UI, not the command line. Happy to, though. It's a pretty silly trivial change.

**Comment by bergey** [comment]
In that case, I'll take care of it.

**Comment by GetContented** [comment]
Cool, thanks. Sorry!

**Pull request closed without merging**
