### PR TITLE
bump bounds on aeson

### PR DESCRIPTION
**Pull request by cstrahan**
This is related to:

* https://github.com/ghcjs/ghcjs/pull/356
* https://github.com/ghcjs/ghcjs-boot/pull/27

Going to try to run a build here in a sec.

### CODE REVIEW

**Comment by cstrahan** [comment]
@luite Ok, just confirmed that this - along with linked PRs - works.

**Comment by cstrahan** [comment]
@luite Do these PRs look good? Perhaps they can be merged? :smile:

**Comment by cstrahan** [comment]
@luite Does this look good?

**Comment by luite** [comment]
sorry for being distracted

**Comment by cstrahan** [comment]
@luite No worries - thanks!

**Pull request merged**
