### PR TITLE
Bump aeson upper bound to 1.1

### PR DESCRIPTION
**Pull request by spl**

### CODE REVIEW

**Comment by spl** [comment]
Does this change require changing shims? I'm now seeing this error in my app, and I think it's related to using `aeson-1.0.2.0`.

```
uncaught exception in Haskell thread: ReferenceError: h$_js_decode_string is not defined
all.js:7069 ReferenceError: h$_js_decode_string is not defined
    at h$$kyZ (all.js:535090)
    at h$runThreadSlice (all.js:8018)
    at h$runThreadSliceCatch (all.js:7968)
    at h$mainLoop (all.js:7963)
    at all.js:8506
    at XMLHttpRequest.load (all.js:23707)
```

Related: https://github.com/bos/aeson/issues/471

**Comment by tolysz** [comment]
My best guess is to have pure Haskell version for this module, and if it is slower and working it is much better then faster and broken. The choice which module to build should be done in `.cabal`

**Comment by alexanderkjeldaas** [comment]
Any solution to this?

**Comment by tolysz** [comment]
The whole module is a simple function for decoding strings, UTF8->UCS2 please write it in Haskell, or "borrow" from some plethora libraries which does it but are not as performing as the C(state machine) version

**Comment by hamishmack** [comment]
Closing this as I think this is out of date now.  The upper bound is currently 1.2 and my understanding is that `aeson-1.1.1.0` includes `ghcjs` support.

**Pull request closed without merging**
